language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - DEPENDENCIES="symfony/lts:^3"
        - PHPUNIT_FLAGS="-v --configuration phpunit.xml.dist --coverage-text"

matrix:
    fast_finish: true
    include:
        # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

        # Test the latest stable release
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4snapshot
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

        # Test LTS versions. This makes sure we do not use Symfony packages with version greater
        # than 3 respectively. Read more at https://github.com/symfony/lts
        - php: 7.1
          env: DEPENDENCIES="symfony/lts:^3"

        # Latest commit to master
        - php: 7.3
          env: STABILITY="dev"

    allow_failures:
        # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - echo 'extension = mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then travis_wait composer config minimum-stability ${STABILITY}; fi;

before_script:
    - composer config platform.ext-mongo 1.6.16
    - composer require --no-update ${DEPENDENCIES}
    - composer require --no-update alcaeus/mongo-php-adapter
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer validate --no-check-lock --strict
    - ./bin/phpunit $PHPUNIT_FLAGS
